config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :submissions, only: [:index, :show, :edit, :update, :destroy] do
      resources :reviews, only: [:create, :destroy]
    end
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  
  #homes
  root to: "public/submissions#top"
  
  #genre
  #歯ブラシ
  get "/submissions/genre1" => "public/submissions#genre1", as: "submission_genre1"
  #歯磨き粉
  get "/submissions/genre2" => "public/submissions#genre2", as: "submission_genre2"
  #補助的清掃用具
  get "/submissions/genre3" => "public/submissions#genre3", as: "submission_genre3"
  #洗口液
  get "/submissions/genre4" => "public/submissions#genre4", as: "submission_genre4"
  #ホワイトニング用品
  get "/submissions/genre5" => "public/submissions#genre5", as: "submission_genre5"
  #口臭ケア用品
  get "/submissions/genre6" => "public/submissions#genre6", as: "submission_genre6"
  
  #submissions
  get "/submissions/new" => "public/submissions#new", as: "new_submission"
  get "/submissions/category" => "public/submissions#category", as: "category_submission"
  get "/submissions" => "public/submissions#index", as: "index_submission"
  get "/submissions/search" => "public/submissions#search", as: "search"
  # get "/submissions/:id" => "public/submissions#show", as: "show_submission"
  namespace :public do
    resources :submissions, only: [:show] do
      resource :favorites, only: [:create, :destroy]
      resources :reviews, only: [:create, :destroy]
    end
    
    resources :customers, only: [] do
      member do
        get :favorites
      end
    end
  end

  get "/submissions/:id/edit" => "public/submissions#edit", as: "edit_submission"
  post "/submissions" => "public/submissions#create", as: "create_submission"
  patch "/submissions/:id" => "public/submissions#update", as: "update_submission"
  delete "/submissions/:id" => "public/submissions#destroy", as: "destroy_submission"
  
  #customers
  get "/customers/:id" => "public/customers#show", as: "show_customer"
  get "/customers/:id/edit" => "public/customers#edit", as: "edit_customer"
  patch "/customers/:id" => "public/customers#update", as: "update_customer"
  get "/customers/:id/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe_customer"
  patch "/customers/:id/withdraw" => "public/customers#withdraw", as: "withdraw_customer"
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
    
  has_many :submissions, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_submissions, through: :favorites, source: :submission
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
     @customer = Customer.find(params[:id])
     @submissions = @customer.submissions
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    customer = Customer.find(params[:id])
    customer.update!(customer_params)
    redirect_to admin_customers_path(params[:id])
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:image, :name, :email, :password, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
   
    <div class="col-12">
      
        <div class="mt-3">
            <h3 class="text-secondary"><strong>会員編集</strong></h3>
        </div>
          
        <div class="row">
          
          <div class="container text-center">
              <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
              <div>
                  <div class="mb-3">
                      プロフィール画像<br>
                      <%= f.file_field :profile_image, accept: "image/*" %>
                  </div>
                  
                  <div class="mb-3">
                       名前<br>
                      <%= f.text_field :name %>
                  </div>
                  
                  <div class="mb-3">
                      アドレス<br>
                      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
                  </div>
                  
                  
                  <div class="mb-3">
                      ステータス<br>
                      <%= f.radio_button :is_deleted, "false" %>
                      <%= f.label :is_deleted, "有効" %>
                  
                      <%= f.radio_button :is_deleted, "true" %>
                      <%= f.label :is_deleted, "退会" %>
                  </div>
                  
                  <div class="px-5 mb-5">
                      <%= f.submit "編集" %>
                  </div>
              </div>
              <% end %>
          </div>
          
        </div>
          
    </div>
    
</div>

app/views/admin/customers/index.html.erb
<div class="container">
   
    <div class="col-12">
      
        <div class="row">
          <div class="mt-3">
            <h3 class="text-secondary"><strong>会員一覧</strong></h3>
          </div>
          
        <div class="container pb-3 mx-5">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>会員ID</th>
                        <th>氏名</th>
                        <th>アドレス</th>
                        <th>ステータス</th>
                    </tr>
                </thead>
                
                <tbody>
                    <% @customers.each do |customer| %>
                    <tr>
                        <th><%= customer.id %></th>
                        <th>
                            <%= link_to admin_customer_path(customer.id) do %>
                            <%= customer.name %>
                            <% end %>
                        </th>
                        <th><%= customer.email %></th>
                        <th>
                            <% if customer.is_deleted %>
                                退会
                            <% else %>
                                有効
                            <% end %>
                        </th>
                    </tr>
                    <% end %>
                </tbody>
            </table>
          
        </div>

    </div>
    
</div>

app/views/admin/customers/show.html.erb
<div class="container">
   
    <div class="col-12">
      
        <div class="row">
          <div class="mt-3">
            <h3 class="text-secondary"><strong>会員詳細</strong></h3>
          </div>
          
        <div class="container pb-3 mx-5">
            <div class="row">
                <div class="col-4 text-center">
                    <p class=""><%= image_tag @customer.get_profile_image(200,200) %></p>
                    
                    <table class="table text-center border">
                        <tbody>
                            <tr>
                                <td class="border-right">会員ID</td>
                                <td><%= @customer.id %></td>
                            </tr>
                            <tr>
                                <td class="border-right">氏名</td>
                                <td><%= @customer.name %></td>
                            </tr>
                            <tr>
                                <td class="border-right">アドレス</td>
                                <td><%= @customer.email %></td>
                            </tr>
                            <tr>
                                <td class="border-right">ステータス</td>
                                <td>
                                    <% if @customer.is_deleted %>
                                        退会
                                    <% else %>
                                        有効
                                    <% end %>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <%= link_to edit_admin_customer_path do %>
                      <button type="button" class="btn btn-secondary">編集</button>
                    <% end %>
                </div>
                
                <div class="col-8 mx-auto mt-3">
                    <div class="mt-3">
                        <h3 class="text-secondary"><strong>投稿一覧</strong></h3>
                    </div>
                    
                    <div class="container py-3 mx-5">
                      <%= render 'admin/submissions/list', submissions: @submissions %>
                    </div>
                </div>
                
                
            </div>
        </div>

    </div>
    
</div>