config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :submissions, only: [:index, :show, :edit, :update, :destroy] do
      resources :reviews, only: [:create, :destroy]
    end
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  
  #homes
  root to: "public/submissions#top"
  
  #genre
  #歯ブラシ
  get "/submissions/genre1" => "public/submissions#genre1", as: "submission_genre1"
  #歯磨き粉
  get "/submissions/genre2" => "public/submissions#genre2", as: "submission_genre2"
  #補助的清掃用具
  get "/submissions/genre3" => "public/submissions#genre3", as: "submission_genre3"
  #洗口液
  get "/submissions/genre4" => "public/submissions#genre4", as: "submission_genre4"
  #ホワイトニング用品
  get "/submissions/genre5" => "public/submissions#genre5", as: "submission_genre5"
  #口臭ケア用品
  get "/submissions/genre6" => "public/submissions#genre6", as: "submission_genre6"
  
  #submissions
  get "/submissions/new" => "public/submissions#new", as: "new_submission"
  get "/submissions/category" => "public/submissions#category", as: "category_submission"
  get "/submissions" => "public/submissions#index", as: "index_submission"
  get "/submissions/search" => "public/submissions#search", as: "search"
  # get "/submissions/:id" => "public/submissions#show", as: "show_submission"
  namespace :public do
    resources :submissions, only: [:show] do
      resource :favorites, only: [:create, :destroy]
      resources :reviews, only: [:create, :destroy]
    end
    
    resources :customers, only: [] do
      member do
        get :favorites
      end
    end
  end

  get "/submissions/:id/edit" => "public/submissions#edit", as: "edit_submission"
  post "/submissions" => "public/submissions#create", as: "create_submission"
  patch "/submissions/:id" => "public/submissions#update", as: "update_submission"
  delete "/submissions/:id" => "public/submissions#destroy", as: "destroy_submission"
  
  #customers
  get "/customers/:id" => "public/customers#show", as: "show_customer"
  get "/customers/:id/edit" => "public/customers#edit", as: "edit_customer"
  patch "/customers/:id" => "public/customers#update", as: "update_customer"
  get "/customers/:id/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe_customer"
  patch "/customers/:id/withdraw" => "public/customers#withdraw", as: "withdraw_customer"
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :submissions, dependent: :destroy
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    # @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genre.id)
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="row">
  <div class="container">
    
      <div class="my-3">
          <h3 class="pb-3 text-secondary">ジャンル編集</h3>
      <div>
          

      <div class="text-center">
          <div class="px-5">
            <%= form_with model: @genre, url: admin_genre_path do |f| %>

              <div class="mb-3">
                <%= f.text_field :name %>
              </div>
              
              <div>
                  <%= f.submit '変更を保存' %>
              </div>
            <% end %>
          </div>
      </div>
      
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
   
    <div class="col-12">
      
        <div class="mt-3">
          <h3 class="text-secondary"><strong>ジャンル一覧・追加</strong></h3>
        </div>
        
        <div class="container pb-3 mx-5">
            
            <!--<div class="text-center">-->
            <!--    %= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>-->
            <!--    <p>ジャンル名</p>-->
            <!--    <p>%= f.text_field :name %></p>-->
            <!--    <p>%= f.submit '新規登録' %></p>-->
            <!--    % end %>-->
            <!--</div>-->
            
            
            <div>
                <table class="table">
                <thead>
                    <tr>
                        <th class="text-center">ジャンル</th>
                        <th colspan="1"></th>
                    </tr>
                </thead>
                
                <tobody>
                    <% @genres.each do |genre| %>
                    <tr>
                        <th class="text-center"><%= genre.name %></th>
                        <th>
                            <div>
                            <%= link_to edit_admin_genre_path(genre.id) do %>
                                <button type="button" class="btn btn-success">編集する</button>
                            <% end %>
                            </div>
                        </th>
                    </tr>
                    <% end %>
                </tobody>
                </table>
            </div>
            
        </div>
    
        
    </div>
    
</div>