config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :submissions, only: [:index, :show, :edit, :update, :destroy] do
      resources :reviews, only: [:create, :destroy]
    end
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  
  #homes
  root to: "public/submissions#top"
  
  #genre
  #歯ブラシ
  get "/submissions/genre1" => "public/submissions#genre1", as: "submission_genre1"
  #歯磨き粉
  get "/submissions/genre2" => "public/submissions#genre2", as: "submission_genre2"
  #補助的清掃用具
  get "/submissions/genre3" => "public/submissions#genre3", as: "submission_genre3"
  #洗口液
  get "/submissions/genre4" => "public/submissions#genre4", as: "submission_genre4"
  #ホワイトニング用品
  get "/submissions/genre5" => "public/submissions#genre5", as: "submission_genre5"
  #口臭ケア用品
  get "/submissions/genre6" => "public/submissions#genre6", as: "submission_genre6"
  
  #submissions
  get "/submissions/new" => "public/submissions#new", as: "new_submission"
  get "/submissions/category" => "public/submissions#category", as: "category_submission"
  get "/submissions" => "public/submissions#index", as: "index_submission"
  get "/submissions/search" => "public/submissions#search", as: "search"
  # get "/submissions/:id" => "public/submissions#show", as: "show_submission"
  namespace :public do
    resources :submissions, only: [:show] do
      resource :favorites, only: [:create, :destroy]
      resources :reviews, only: [:create, :destroy]
    end
    
    resources :customers, only: [] do
      member do
        get :favorites
      end
    end
  end

  get "/submissions/:id/edit" => "public/submissions#edit", as: "edit_submission"
  post "/submissions" => "public/submissions#create", as: "create_submission"
  patch "/submissions/:id" => "public/submissions#update", as: "update_submission"
  delete "/submissions/:id" => "public/submissions#destroy", as: "destroy_submission"
  
  #customers
  get "/customers/:id" => "public/customers#show", as: "show_customer"
  get "/customers/:id/edit" => "public/customers#edit", as: "edit_customer"
  patch "/customers/:id" => "public/customers#update", as: "update_customer"
  get "/customers/:id/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe_customer"
  patch "/customers/:id/withdraw" => "public/customers#withdraw", as: "withdraw_customer"
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
    
  has_many :submissions, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_submissions, through: :favorites, source: :submission
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :customer

    belongs_to :submission
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :submissions, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :customer
    belongs_to :submission
    validates :comment, presence: true
end

app/models/submission.rb
class Submission < ApplicationRecord
    
    validates :name, presence: true
    validates :price, presence: true

    belongs_to :customer
    belongs_to :genre
    
    has_many :reviews, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_customers, through: :favorites, source: :customer
    
    has_one_attached :image
    
    def get_image(width, height)
        unless image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        image.variant(resize_to_limit: [width, height]).processed
    end
    
    def favorited_by?(customer)
        #byebug
      favorites.exists?(customer_id: customer.id)
    end
    
    def self.search(keyword)
        where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    # @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path(genre.id)
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  def create
    submission = Submission.find(params[:submission_id])
    review.submission_id = submission.id
    review.save
    redirect_to admin_submission_path(submission)
  end
  
  def destroy
    Review.find(params[:id]).destroy
    redirect_to admin_submission_path(params[:submission_id])
  end
  
  private

  def review_params
    params.require(:review).permit(:comment, :star)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  protected
  
  def after_sign_in_path_for(resource)
    admin_submissions_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/submissions_helper.rb
module Admin::SubmissionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShinySmiles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

    
  <body>
    <header class="border-bottom border-3 border-dark">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        
          <% if admin_signed_in? %>
            <div class="navbar-brand">
              <%= link_to admin_submissions_path do %>
                <button type="button" class="btn btn-light">
                  <h1 class="text-secondary"><strong>Shiny Smiles</strong></h1>
                </button>
              <% end %>
            </div>
          <% else %>
            <div class="navbar-brand">
              <%= link_to root_path do %>
                <button type="button" class="btn btn-light">
                  <h1 class="text-secondary"><strong>Shiny Smiles</strong></h1>
                </button>
              <% end %>
            </div>
          <% end %>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
          <ul class="navbar-nav ml-auto">
            
            <% if customer_signed_in? %>
            
              <li class="nav-item my-1 mx-1">
                <%= link_to category_submission_path do %>
                <button type="button" class="btn btn-secondary">検索</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1">
                <%= link_to new_submission_path do %>
                <button type="button" class="btn btn-secondary">投稿</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1">
                <%= link_to favorites_public_customer_path(current_customer.id) do %>
                <button type="button" class="btn btn-secondary">♡</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1">
                <%= link_to show_customer_path(current_customer.id) do %>
                <button type="button" class="btn btn-secondary">マイページ</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1">
                <%= link_to destroy_customer_session_path, method: :delete do %>
                <button type="button" class="btn btn-secondary">ログアウト</button>
                <% end %>
              </li>
              
            <% elsif admin_signed_in? %>
            
              <li class="nav-item my-1 mx-1">
                <%= link_to admin_submissions_path do %>
                <button type="button" class="btn btn-secondary">投稿一覧</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1">
                <%= link_to admin_customers_path do %>
                <button type="button" class="btn btn-secondary">会員一覧</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1">
                <%= link_to admin_genres_path do %>
                <button type="button" class="btn btn-secondary">ジャンル</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1">
                <%= link_to destroy_admin_session_path, method: :delete do %>
                <button type="button" class="btn btn-secondary">ログアウト</button>
                <% end %>
              </li>
            
            <% else %>
            
              <li class="nav-item my-1 mx-1">
                <%= link_to category_submission_path do %>
                <button type="button" class="btn btn-secondary">検索</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1">
                <%= link_to new_customer_registration_path do %>
                <button type="button" class="btn btn-secondary">会員登録</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1">
                <%= link_to new_customer_session_path do %>
                <button type="button" class="btn btn-secondary">ログイン</button>
                <% end %>
              </li>
              <li class="nav-item my-1 mx-1"></li>
              
            <% end %>
            
          </ul>
        </div>
        
      </nav>
    </header>
    
    <main>
    <%= yield %>
    </main>

    <footer class="border-top border-3 border-dark bg-secondary">
      <p class="text-center py-4 text-white">footer</p>
    </footer>

  </body>
</html>