config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :submissions, only: [:index, :show, :edit, :update, :destroy] do
      resources :reviews, only: [:create, :destroy]
    end
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
  end
  
  #homes
  root to: "public/submissions#top"
  
  #genre
  #歯ブラシ
  get "/submissions/genre1" => "public/submissions#genre1", as: "submission_genre1"
  #歯磨き粉
  get "/submissions/genre2" => "public/submissions#genre2", as: "submission_genre2"
  #補助的清掃用具
  get "/submissions/genre3" => "public/submissions#genre3", as: "submission_genre3"
  #洗口液
  get "/submissions/genre4" => "public/submissions#genre4", as: "submission_genre4"
  #ホワイトニング用品
  get "/submissions/genre5" => "public/submissions#genre5", as: "submission_genre5"
  #口臭ケア用品
  get "/submissions/genre6" => "public/submissions#genre6", as: "submission_genre6"
  
  #submissions
  get "/submissions/new" => "public/submissions#new", as: "new_submission"
  get "/submissions/category" => "public/submissions#category", as: "category_submission"
  get "/submissions" => "public/submissions#index", as: "index_submission"
  get "/submissions/search" => "public/submissions#search", as: "search"
  # get "/submissions/:id" => "public/submissions#show", as: "show_submission"
  namespace :public do
    resources :submissions, only: [:show] do
      resource :favorites, only: [:create, :destroy]
      resources :reviews, only: [:create, :destroy]
    end
    
    resources :customers, only: [] do
      member do
        get :favorites
      end
    end
  end

  get "/submissions/:id/edit" => "public/submissions#edit", as: "edit_submission"
  post "/submissions" => "public/submissions#create", as: "create_submission"
  patch "/submissions/:id" => "public/submissions#update", as: "update_submission"
  delete "/submissions/:id" => "public/submissions#destroy", as: "destroy_submission"
  
  #customers
  get "/customers/:id" => "public/customers#show", as: "show_customer"
  get "/customers/:id/edit" => "public/customers#edit", as: "edit_customer"
  patch "/customers/:id" => "public/customers#update", as: "update_customer"
  get "/customers/:id/unsubscribe" => "public/customers#unsubscribe", as: "unsubscribe_customer"
  patch "/customers/:id/withdraw" => "public/customers#withdraw", as: "withdraw_customer"
  
end

app/models/submission.rb
class Submission < ApplicationRecord
    
    validates :name, presence: true
    validates :price, presence: true

    belongs_to :customer
    belongs_to :genre
    
    has_many :reviews, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorited_customers, through: :favorites, source: :customer
    
    has_one_attached :image
    
    def get_image(width, height)
        unless image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        image.variant(resize_to_limit: [width, height]).processed
    end
    
    def favorited_by?(customer)
        #byebug
      favorites.exists?(customer_id: customer.id)
    end
    
    def self.search(keyword)
        where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
    end
end

app/controllers/admin/submissions_controller.rb
class Admin::SubmissionsController < ApplicationController
  def index
    @submissions = Submission.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @submission = Submission.find(params[:id])
  end

  def edit
    @submission = Submission.find(params[:id])
  end
  
  def update
    @submission = Submission.find(params[:id])
    if @submission.update(submission_params)
      redirect_to admin_submission_path(@submission.id)
    else
      render "edit"
    end
  end
  
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to admin_submissions_path
  end
  
  def submission_params
    params.require(:submission).permit(:name, :image, :genre_id, :price, :introduction)
  end
end

app/helpers/admin/submissions_helper.rb
module Admin::SubmissionsHelper
end

app/views/admin/submissions/_list.html.erb
<% submissions.each do |submission| %>
  <%= link_to admin_submission_path(submission.id) do %>
  <div class="row border border-dark mb-3 pt-3">
    <div class="col-4">
      <p class="">
        <%= image_tag submission.get_image(100,100) %>
      </p>
    </div>
    
    <div class="col-8">
      <p class="h5 text-dark">
        <strong><%= submission.name %></strong>
      </p>
      
      <p class="ml-3 text-dark">
        <strong><%= submission.introduction %></strong>
      </p>
      
      <p class="text-dark text-right">
        <span class="mr-2">♥（<%= submission.favorited_customers.count %>）</span>
        コメント（<%= submission.reviews.count %>）
      </p>
      
      <p>
        <div class="text-dark text-right">
          <%= image_tag submission.customer.get_profile_image(30,30) %>
          <%= submission.customer.name %>
        </div>
      </p>
      
    </div>
  </div>
  <% end %>
<% end %>

app/views/admin/submissions/edit.html.erb
<div class="container">
   
    <div class="col-12">
      
        <div class="my-3">
            <h3 class="text-secondary"><strong>投稿編集</strong></h3>
        </div>
          
        <div class="text-center">
            <%= form_with model: @submission, url: admin_submission_path(@submission.id), method: :patch do |f| %>
            <div>
                <div class="mb-3">
                    <p>
                        画像 <br> <%= f.file_field :image, accept: "image/*" %>
                    </p>
                </div>
                
                <div class="mb-3">
                    <p>
                        商品名 <br> <%= f.text_field :name %>
                    </p>
                </div>
                
                <div class="mb-3">
                    <p>
                        ジャンル <br> <%= f.select :genre_id, [['歯ブラシ',1], ['歯磨き粉',2], ['補助的清掃用具',3], ['洗口液',4], ['ホワイトニング用品',5], ['口臭ケア用品',6]] %>
                    </p>
                </div>
                
                <div class="mb-3">
                    <p>
                        値段 <br> <span><%= f.text_field :price %>円（定価）</span>
                    </p>
                </div>
                
                <div class="mb-3">
                    <p>
                        説明 <br> <%= f.text_area :introduction %>
                    </p>
                </div>
                
                <div class="mb-5">
                    <%= f.submit '編集' %>
                </div>
            </div>
            <% end %>
        </div>
        
    </div>
    
</div>

app/views/admin/submissions/index.html.erb
<div class="container">
   
    <div class="col-12">
      
        <div class="row">
          <div class="mt-3">
            <h3 class="text-secondary"><strong>投稿一覧</strong></h3>
          </div>
          
        <div class="container pb-3 mx-5">
          <%= render 'list', submissions: @submissions %>
        </div>
        
        <div class="mb-3 mx-5">
              <%= paginate @submissions %>
        </div>

    </div>
    
</div>

app/views/admin/submissions/show.html.erb
<div class="container">
    
    <div class="col-12">
      
        <div class="my-3">
            <h3 class="text-secondary"><strong>投稿詳細</strong></h3>
        </div>
        
        <div class="container py-3 mx-5">
          
            <div class="row">
                <div class="col-5 px-2">   
                    <%= image_tag @submission.get_image(400,400) %>
                </div> 
                
                <div class="col-7">
                    <div class="row mb-5">
                        <h5 class="col-9"><strong><%= @submission.name %></strong></h5>
                        
                        <span class="h5 ml-3 text-danger">♥<%= @submission.favorited_customers.count %></span>
                    </div>
                    
                    <div class="ml-3">
                        <table>
                            <tbody>
                                <tr>
                                    <td><p class="text-right">ジャンル：</p></td>
                                    <td>
                                        <p class="ml-2">
                                        <% if @submission.genre_id == 1 %>
                                          歯ブラシ
                                        <% elsif @submission.genre_id == 2 %>
                                          歯磨き粉
                                        <% elsif @submission.genre_id == 3 %>
                                          補助的清掃用具
                                        <% elsif @submission.genre_id == 4 %>
                                          洗口液
                                        <% elsif @submission.genre_id == 5 %>
                                          ホワイトニング用品
                                        <% else @submission.genre_id == 6 %>
                                          口臭ケア用品
                                        <% end %>
                                        </p>
                                    </td>
                                </tr>
                                
                                <tr>
                                    <td><p class="text-right">値段：</p></td>
                                    <td><p class="ml-2">¥<%= @submission.price %>円（定価）</p></td>
                                </tr>
                                
                                <tr>
                                    <td><p class="text-right">説明：</p></td>
                                    <td><p class="ml-2"><%= @submission.introduction %></p></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                    <div class="text-right">
                        <%= link_to admin_customer_path(@submission.customer.id) do %>
                        <div class="text-dark">
                            <%= image_tag @submission.customer.get_profile_image(70,70) %>
                            <%= @submission.customer.name %>
                        </div>
                        <% end %>
                    </div>
                    
                    <div class="text-right">
                            <%= link_to edit_admin_submission_path(@submission.id) do %>
                            <button type="button" class="btn btn-secondary">編集する</button>
                            <% end %>
                        
                            <%= link_to admin_submission_path(@submission.id), method: :delete do %>
                            <button type="button" class="btn btn-secondary">削除する</button>
                            <% end %>
                    </div>
                      
                    <div class="text-right">
                        <%= @submission.created_at.strftime('%Y/%m/%d') %>
                    </div>
                    
                </div>
            </div>
        </div>
          
          
         <!--コメント-->
        <div class="container py-3 mx-5">

            <p><strong>コメント（<%= @submission.reviews.count %>）</strong></p>
            
            <div class="row">
            <% @submission.reviews.each do |review| %>
            <div class="col-10 mx-auto border border-dark mb-3 py-3 px-3">
                <div class""><%= review.comment %></div>
                <div class="text-right">
                    <span><%= image_tag @submission.customer.get_profile_image(50,50) %></span>
                    <span><%= review.customer.name %></span>
                    <span><%= review.created_at.strftime('%Y/%m/%d') %></span>
                    <span>
                        <%= link_to "削除", admin_submission_review_path(review.submission, review), method: :delete %>
                    </span>
                </div>
            </div>
            <% end %>
            </div>

        </div>
      
    </div>
    
</div>